# Metastable Zr tracer calculation

In [1]:
import numpy as np
from onsager import OnsagerCalc
from onsager import crystal
import textwrap
import matplotlib.pyplot as plt
import yaml
%matplotlib inline
from scipy.constants import physical_constants
kB = physical_constants['Boltzmann constant in eV/K'][0]
#print (kB)

In [2]:
a= 3.2342373809
c_a= 1.5989108537
c=a*c_a
HCP = crystal.Crystal.HCP(a0=a,c_a=c_a, chemistry="Zr")
print(HCP)

#Lattice:
  a1 = [ 1.61711869 -2.80093173  0.        ]
  a2 = [ 1.61711869  2.80093173  0.        ]
  a3 = [ 0.          0.          5.17125725]
#Basis:
  (Zr) 0.0 = [ 0.33333333  0.66666667  0.25      ]
  (Zr) 0.1 = [ 0.66666667  0.33333333  0.75      ]


In [3]:
x1=[0.15128245,  0.07426086,  0.48753938]
x2=[0,0,0.5]
print(np.linalg.norm(HCP.lattice.dot(x1)-HCP.lattice.dot(x2)))

0.428626548777


In [10]:
#site = [0.3030904148327712,  0.2751389116789031,  0.1637588113305137] # OC Oct
#site = [ 0.2641298286213796,  0.2358701713786205,  0.0833333333333357] BC
site = np.array([ 0.2358701713786205,  0.2217403427572409,  0.25000000000000]) # DFC2
for i in range(2):
    if abs(site[i]> 0.25): site[i]-=0.25
    site[i]*=4
site[-1]*=3   
#site = np.array([ 0.2579643384641777,0.9920356615358923,0.2500000000000000]) # DFC2
x=HCP.Wyckoffpos(np.array(site))
#np.set_printoptions(precision=16)
#for i in x:
#    y = HCP.lattice.dot(i)
#    #y[0]+=a
#    print(y)

In [12]:
np.set_printoptions(16)
x

[array([ 0.0565193144855179,  0.9434806855144815,  0.25              ]),
 array([ 0.8869613710289636,  0.9434806855144821,  0.25              ]),
 array([ 0.9434806855144821,  0.0565193144855185,  0.75              ]),
 array([ 0.9434806855144815,  0.8869613710289636,  0.75              ]),
 array([ 0.0565193144855185,  0.1130386289710364,  0.25              ]),
 array([ 0.1130386289710364,  0.0565193144855185,  0.75              ])]

In [9]:
np.set_printoptions(16)
x

[array([ 0.9681426461432892,  0.9362852922868583,  0.25              ]),
 array([ 0.9681426461435692,  0.0318573538567108,  0.25              ]),
 array([ 0.0318573538567108,  0.0637147077131417,  0.75              ]),
 array([ 0.9362852922868583,  0.9681426461435692,  0.75              ]),
 array([ 0.0637147077131417,  0.0318573538564308,  0.25              ]),
 array([ 0.0318573538567108,  0.9681426461435692,  0.75              ])]

In [6]:
s1 = np.array([ 0.7876383406689151,  0.8994443532843877,  0.9912764339915411])
s2 = np.array([ 0.7876383406689151,  0.8881939873845275,  0.9912764339915411])
(s1+s2)/2

array([ 0.7876383406689151,  0.8938191703344576,  0.9912764339915411])

In [11]:
zlist = [z[-2] for z in x]


In [13]:
for i in x:
    print(repr(i[0]),repr(i[1]),repr(i[2]))

0.0 0.82337861164334325 0.5
0.0 0.17662138835665681 0.5
0.82337861164334325 0.82337861164334325 0.5
0.82337861164334325 0.82337861164334325 0.0
0.0 0.82337861164334325 0.0
0.0 0.17662138835665681 0.0
0.17662138835665681 0.17662138835665681 0.5
0.82337861164334325 0.0 0.5
0.17662138835665681 0.17662138835665681 0.0
0.82337861164334325 0.0 0.0
0.17662138835665681 0.0 0.0
0.17662138835665681 0.0 0.5


In [5]:
for i in x:
    y = HCP.lattice.dot(i)
    print("Fe     ",y[0],y[1],y[2])

Fe      2.86727487284 0.211865921485 2.65006569742
Fe      0.366962524234 0.211865893476 2.65006569742
Fe      2.86727487284 -0.211865921485 0.0644370715365
Fe      2.86727487284 0.211865921485 5.10682018023
Fe      1.61711870662 2.37719991877 2.65006569742
Fe      1.61711867428 -2.37719991877 2.52119155435
Fe      1.61711870662 2.37719991877 5.10682018023
Fe      1.61711867428 -2.37719991877 0.0644370715365
Fe      0.366962508063 -0.211865921485 2.52119155435
Fe      2.86727487284 -0.211865921485 2.52119155435
Fe      0.366962524234 0.211865893476 5.10682018023
Fe      0.366962524234 -0.211865893476 0.0644370715365


In [8]:
HCP.lattice.dot([ 0.16843,  0.     ,  0.5    ])

array([ 0.2723713 , -0.47176093,  2.58562863])

In [5]:
meta_basis = HCP.Wyckoffpos(np.array([5/6,2/3,0.25]))
print(meta_basis)

[array([ 0.16666667,  0.33333333,  0.75      ]), array([ 0.16666667,  0.83333333,  0.75      ]), array([ 0.66666667,  0.83333333,  0.75      ]), array([ 0.83333333,  0.66666667,  0.25      ]), array([ 0.83333333,  0.16666667,  0.25      ]), array([ 0.33333333,  0.16666667,  0.25      ])]


In [6]:
basis = HCP.basis[0] + meta_basis
print(basis, len(basis))

[array([ 0.33333333,  0.66666667,  0.25      ]), array([ 0.66666667,  0.33333333,  0.75      ]), array([ 0.16666667,  0.33333333,  0.75      ]), array([ 0.16666667,  0.83333333,  0.75      ]), array([ 0.66666667,  0.83333333,  0.75      ]), array([ 0.83333333,  0.66666667,  0.25      ]), array([ 0.83333333,  0.16666667,  0.25      ]), array([ 0.33333333,  0.16666667,  0.25      ])] 8


In [5]:
crys = crystal.Crystal(HCP.lattice, basis[0:8], chemistry=["Zr"], noreduce=True)
# crys = HCP.addbasis(meta_basis)
print(crys)

#Lattice:
  a1 = [ 1.61711869 -2.80093173  0.        ]
  a2 = [ 1.61711869  2.80093173  0.        ]
  a3 = [ 0.          0.          5.17125725]
#Basis:
  (Zr) 0.0 = [ 0.33333333  0.66666667  0.25      ]
  (Zr) 0.1 = [ 0.66666667  0.33333333  0.75      ]
  (Zr) 0.2 = [ 0.16666667  0.33333333  0.75      ]
  (Zr) 0.3 = [ 0.83333333  0.66666667  0.25      ]
  (Zr) 0.4 = [ 0.66666667  0.83333333  0.75      ]
  (Zr) 0.5 = [ 0.83333333  0.16666667  0.25      ]
  (Zr) 0.6 = [ 0.33333333  0.16666667  0.25      ]
  (Zr) 0.7 = [ 0.16666667  0.83333333  0.75      ]


In [6]:
#in_f=open('HCP-Vac-Meta.yaml', "r")
#dict_def = crystal.yaml.load(in_f)
#in_f.close()
#crys = crystal.Crystal.fromdict(dict_def) # pull out the crystal part of the YAML
#print(crys)
#crys.sitelist(0)

In [6]:
sitelist = crys.sitelist(0)
vacancyjumps = crys.jumpnetwork(0, 1.01*a)
for jlist in vacancyjumps:
    print('---')
    for (i,j), dx in jlist:
        print(i, '-', j, dx,np.linalg.norm(dx))

---
1 - 1 [  3.23423738e+00   1.11022302e-16   0.00000000e+00] 3.2342373809
1 - 1 [ -3.23423738e+00  -1.11022302e-16  -0.00000000e+00] 3.2342373809
0 - 0 [-1.61711869 -2.80093173  0.        ] 3.2342373809
0 - 0 [ 1.61711869  2.80093173 -0.        ] 3.2342373809
1 - 1 [ 1.61711869  2.80093173  0.        ] 3.2342373809
1 - 1 [-1.61711869 -2.80093173 -0.        ] 3.2342373809
1 - 1 [-1.61711869  2.80093173  0.        ] 3.2342373809
1 - 1 [ 1.61711869 -2.80093173 -0.        ] 3.2342373809
0 - 0 [  3.23423738e+00  -1.11022302e-16   0.00000000e+00] 3.2342373809
0 - 0 [ -3.23423738e+00   1.11022302e-16  -0.00000000e+00] 3.2342373809
0 - 0 [-1.61711869  2.80093173  0.        ] 3.2342373809
0 - 0 [ 1.61711869 -2.80093173 -0.        ] 3.2342373809
---
1 - 0 [ 1.61711869 -0.93364391  2.58562863] 3.18939480199
0 - 1 [-1.61711869  0.93364391 -2.58562863] 3.18939480199
0 - 1 [ 0.         -1.86728782  2.58562863] 3.18939480199
1 - 0 [-0.          1.86728782 -2.58562863] 3.18939480199
1 - 0 [ 0.      

In [7]:
jumpnetwork = [vacancyjumps[1], vacancyjumps[3]]
jumpnetwork2 = [vacancyjumps[1], vacancyjumps[0]]
for jlist in jumpnetwork:
    print('---')
    for (i,j), dx in jlist:
        print(i, '-', j, dx,np.linalg.norm(dx))

---
1 - 0 [ 1.61711869 -0.93364391  2.58562863] 3.18939480199
0 - 1 [-1.61711869  0.93364391 -2.58562863] 3.18939480199
0 - 1 [ 0.         -1.86728782  2.58562863] 3.18939480199
1 - 0 [-0.          1.86728782 -2.58562863] 3.18939480199
1 - 0 [ 0.          1.86728782  2.58562863] 3.18939480199
0 - 1 [-0.         -1.86728782 -2.58562863] 3.18939480199
0 - 1 [ 1.61711869  0.93364391  2.58562863] 3.18939480199
1 - 0 [-1.61711869 -0.93364391 -2.58562863] 3.18939480199
0 - 1 [ 1.61711869  0.93364391 -2.58562863] 3.18939480199
1 - 0 [-1.61711869 -0.93364391  2.58562863] 3.18939480199
0 - 1 [-1.61711869  0.93364391  2.58562863] 3.18939480199
1 - 0 [ 1.61711869 -0.93364391 -2.58562863] 3.18939480199
---
1 - 2 [ 0.80855935 -1.40046587  0.        ] 1.61711869045
2 - 1 [-0.80855935  1.40046587 -0.        ] 1.61711869045
0 - 3 [ 0.80855935 -1.40046587  0.        ] 1.61711869045
3 - 0 [-0.80855935  1.40046587 -0.        ] 1.61711869045
1 - 2 [-0.80855935  1.40046587  0.        ] 1.61711869045
2 - 1 

In [9]:
crys.sitelist(0)

[[0, 1], [2, 3, 4, 5, 6, 7]]

In [8]:
HCPdiffuser = OnsagerCalc.VacancyMediatedMeta(crys, 0, sitelist, jumpnetwork, 2, meta_tags = [False,True], jumpnetwork2= jumpnetwork2)
#HCPdiffuser.omegalist()

In [9]:
HCPdiffuser.N

8

In [10]:
HCPdiffuser.interactlist()

[PairState(i=0, j=4, R=array([0, 0, 0]), dx=array([ -2.22044605e-16,   9.33643911e-01,   2.58562863e+00])),
 PairState(i=0, j=1, R=array([0, 0, 0]), dx=array([-0.        , -1.86728782,  2.58562863])),
 PairState(i=0, j=0, R=array([-1,  0,  0]), dx=array([-1.61711869,  2.80093173,  0.        ])),
 PairState(i=0, j=2, R=array([0, 1, 0]), dx=array([ 0.80855935,  2.33410978,  2.58562863])),
 PairState(i=1, j=6, R=array([ 0, -1,  0]), dx=array([-2.42567804, -2.33410978, -2.58562863])),
 PairState(i=0, j=0, R=array([0, 0, 1]), dx=array([  0.00000000e+00,  -2.22044605e-16,   5.17125725e+00])),
 PairState(i=0, j=0, R=array([-1,  0, -1]), dx=array([-1.61711869,  2.80093173, -5.17125725]))]

In [10]:
HCPdiffuser.omegalist(2)
#HCPdiffuser.om2_jt=[1,0]

([(PairState(i=0, j=1, R=array([ 0,  1, -1]), dx=array([ 1.61711869,  0.93364391, -2.58562863])),
   PairState(i=1, j=0, R=array([ 0, -1,  1]), dx=array([-1.61711869, -0.93364391,  2.58562863]))),
  (PairState(i=1, j=1, R=array([1, 1, 0]), dx=array([  3.23423738e+00,  -1.11022302e-16,   0.00000000e+00])),
   PairState(i=1, j=1, R=array([-1, -1,  0]), dx=array([ -3.23423738e+00,  -1.11022302e-16,   0.00000000e+00])))],
 [0, 1])

In [11]:
HCPdiffuser.om0_jn

[[((1, 0), array([-1.61711869, -0.93364391,  2.58562863])),
  ((0, 1), array([ 1.61711869,  0.93364391, -2.58562863])),
  ((0, 1), array([-1.61711869,  0.93364391, -2.58562863])),
  ((1, 0), array([ 1.61711869, -0.93364391,  2.58562863])),
  ((0, 1), array([-1.61711869,  0.93364391,  2.58562863])),
  ((1, 0), array([ 1.61711869, -0.93364391, -2.58562863])),
  ((0, 1), array([ 0.        , -1.86728782, -2.58562863])),
  ((1, 0), array([-0.        ,  1.86728782,  2.58562863])),
  ((0, 1), array([ 1.61711869,  0.93364391,  2.58562863])),
  ((1, 0), array([-1.61711869, -0.93364391, -2.58562863])),
  ((1, 0), array([ 0.        ,  1.86728782, -2.58562863])),
  ((0, 1), array([-0.        , -1.86728782,  2.58562863]))],
 [((1, 5), array([-0.80855935,  1.40046587,  0.        ])),
  ((5, 1), array([ 0.80855935, -1.40046587, -0.        ])),
  ((0, 4), array([ 0.80855935, -1.40046587,  0.        ])),
  ((4, 0), array([-0.80855935,  1.40046587, -0.        ])),
  ((0, 3), array([-0.80855935, -1.40046

In [14]:
#HCPdiffuser = OnsagerCalc.VacancyMediated(HCP2, 0, sitelist, vacancyjumps, 1)
#HCPdiffuser = OnsagerCalc.VacancyMediated(crys, 0, sitelist, jumpnetwork, 1)
#HCPdiffuser.omegalist()

We need to specify the vacancy prefactor and formation energy, though the $L_{ij}$ needs to be explicitely multiplied by $c_\text{v}$, so it is *strictly used as a reference for the transition state energies*.

In [9]:
#HCPtracer = {'preV': np.array([1.0/1.1075157070506694]), 'eneV': np.array([0.0]), 
#             'preT0': np.array([129.2186479/36.7840204101001, 129.2186479/34.5772672908345]), 'eneT0': np.array([1.211, 1.23])}
#HCPtracer = {'preV': np.array([1.0,54.169024409/18.299152044]), 'eneV': np.array([2.0, 2.0 + 0.517269999999973]), 
#             'preT0': np.array([ 54.169024409/9.26073917, 54.169024409/10.40702378]), 
#             'eneT0': np.array([0.613339999999994, 0.553549999999973]),
#              }
HCPtracer = {'preV': np.array([1.0,54.169024409/18.299152044]), 'eneV': np.array([0.0, 0.517269999999973]), 
             'preT0': np.array([ 54.169024409/9.26073917, 54.169024409/10.40702378]), 
             'eneT0': np.array([0.613339999999994, 0.553549999999973]),
              }

HCPtracer.update(HCPdiffuser.maketracerpreene(**HCPtracer))

Anisotropic diffusivity from Onsager calculation; needs to be multiplied by $c_\text{v}/k_\text{B}T$ to make $L$ for the vacancy or $c_\text{v}c_\text{s}/k_\text{B}T$ for the solute (or solute/vacancy). To get the diffusivity of the tracer, we will need to multiply by $c_\text{v}$ only.

In [10]:
HCPtracer

{'eneS': array([ 0.,  0.]),
 'eneSV': array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.]),
 'eneT0': array([ 0.61334,  0.55355]),
 'eneT1': array([ 0.61334,  0.61334,  0.61334,  0.61334,  0.61334,  0.61334,
         0.61334,  0.61334,  0.61334,  0.61334,  0.61334,  0.55355,
         0.55355,  0.55355,  0.55355,  0.55355]),
 'eneT2': array([ 0.61334,  0.55355]),
 'eneV': array([ 0.     ,  0.51727]),
 'preS': array([ 1.,  1.]),
 'preSV': array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.]),
 'preT0': array([ 5.84931974,  5.20504474]),
 'preT1': array([ 5.84931974,  5.84931974,  5.84931974,  5.84931974,  5.84931974,
         5.84931974,  5.84931974,  5.84931974,  5.84931974,  5.84931974,
         5.84931974,  5.20504474,  5.20504474,  5.20504474,  5.20504474,
         5.20504474]),
 'preT2': array([ 5.84931974,  5.20504474]),
 'preV': array([ 1.        ,  2.96019314])}

In [10]:
HCPtracer['preT2'] = np.array([54.169024409/9.26073917, 0.5*54.169024409/10.40702378])

In [11]:
#Temp=np.arange(500, 1010, 100)
#Temp = [500,1000]
Temp = [1000]
D_Onsager=[]
for T in Temp:
    pre=1e-8 # THz and Angstrom unit scaling
    Lvv, Lss, Lsv, L1vv = HCPdiffuser.Lij(*HCPdiffuser.preene2betafree(kB*T, **HCPtracer))
    Lss=Lss*pre
    D_Onsager.append([Lss[0,0],Lss[1,1],Lss[2,2]])
    print(T, Lvv[0,0],Lvv[1,1],Lvv[2,2])
    print(T, Lsv[0,0]/Lvv[0,0],Lsv[1,1]/Lvv[1,1],Lsv[2,2]/Lvv[2,2])

D_Onsager=np.array(D_Onsager)

biasVvec
[  1.54744318e-13   4.12651514e-13  -2.77555756e-17  -5.87775605e-18
   9.36055934e-02  -2.93887802e-18  -8.93588472e-13   6.70698363e-13
  -6.68670327e-13   0.00000000e+00   1.00503353e-12   4.45780218e-13
   4.91128009e-18  -9.66475961e-19   1.07890361e-17   2.15780723e-17
  -2.77555756e-17   2.77555756e-17   0.00000000e+00   0.00000000e+00
   0.00000000e+00   2.77555756e-17  -6.93889390e-18   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
biasSvec
[ -0.00000000e+00  -0.00000000e+00   1.03662270e-01  -1.87501412e-17
   9.36055934e-02  -0.00000000e+00  -0.00000000e+00  -0.00000000e+00
  -0.00000000e+00  -0.00000000e+00  -0.00000000e+00  -0.00000000e+00
  -0.00000000e+00  -0.00000000e+00  -0.00000000e+00  -0.00000000e+00
  -0.00000000e+00  -0.00000000e+00  -0.00000000e+00  -0.00000000e+00
  -0.00000000e+00  -0.00000000e+00  -0.00000000e+00  -0.00000000e+00
  -0.00000000e+00  -0.00000000e+00  -0.00000000e+00  -0.00000000e+00]
L0vv
[[  8.910

In [12]:
D_Onsager

array([[  8.39181998e-10,   8.39181998e-10,   8.78024912e-10]])

In [35]:
(-2.07631261e-02)*0.92+ 8.91089813e-02

0.070006905288

# Analytical tracer diffusion result

We take the tabular data directly from Koiwa and Ishioka's paper (doi://10.1080/01418618308245263) in tabular form, put it here and use spline interpolation instead of the polynomial ratios. This is mainly to get the exact values when the particular ratio is calculated.

In [8]:
#Correlations from Koiwa and Ishioka’s
# def fz(x):
#     return((1+8.77*x+7.37*x**2+0.65*x**3)/(1+9.90*x+10.9*x**2+x**3))
# def fx(x):
#     return((0.56+4.38*x+3.67*x**2+0.64*x**3)/(1+5.75*x+4.11*x**2+x**3))
from scipy import interpolate
# nuB / nuA
nuBA = np.arange(0.0, 1.0001, 0.1)
fxBAraw = np.array([0.560057, 0.642376, 0.683451, 0.711016, 0.730851, 0.745626, 
                    0.756849, 0.765469, 0.772123, 0.777260, 0.781205])
fzBAraw = np.array([1.000000, 0.929038, 0.892655, 0.866949, 0.847185, 0.831277, 
                    0.818082, 0.806901, 0.797270, 0.788865, 0.781451])
fxBA = interpolate.UnivariateSpline(nuBA, fxBAraw, s=0)
fzBA = interpolate.UnivariateSpline(nuBA, fzBAraw, s=0)
# nuA / nuB
nuAB = np.arange(1.0, -0.0001, -0.1)
fxABraw = np.array([0.781205, 0.784485, 0.787315, 0.789404, 0.790295, 0.789251, 
                    0.785032, 0.775451, 0.756394, 0.719387, 0.644545])
fzABraw = np.array([0.781451, 0.774166, 0.766204, 0.757451, 0.747762, 0.736951, 
                    0.724773, 0.710893, 0.694845, 0.675941, 0.653109])
fxAB = interpolate.UnivariateSpline(nuAB[::-1], fxABraw[::-1], s=0)
fzAB = interpolate.UnivariateSpline(nuAB[::-1], fzABraw[::-1], s=0)
def fx(x):
    if x <= 1: return fxBA(x)
    else: return fxAB(1/x)
def fz(x):
    if x <= 1: return fzBA(x)
    else: return fzAB(1/x)

In [9]:
def Basal_rate(T):
    prefactor=(129.2186479/36.78402041)
    mb=0.397
    return(prefactor*np.exp(-mb/(kB*T)))
def c_rate(T):
    prefactor=(129.2186479/34.57726729)
    mc=0.416
    return(prefactor*np.exp(-mc/(kB*T)))

In [10]:
def Vconc(T):
    entropy_contribution=1.1075157070506694
    formationE=0.814228281
    prob=entropy_contribution*np.exp(-formationE/(kB*T))
    return(prob)

In [11]:
def AnalyticalD(T):
    wb=Basal_rate(T)
    wc=c_rate(T)
    x=wc/wb  # NOTE: this was reversed in the code Ravi sent; I'm putting it back to the definition in K&S 1983 paper
    c=a*c_a
    Dxx=0.5*Vconc(T)*a**2*fx(x)*(3*wb+wc)
    Dzz=0.75*Vconc(T)*c**2*fz(x)*wc
    return(np.array([Dxx,Dxx,Dzz]))

In [12]:
D_Analytical=[]
vac = np.array([Vconc(T) for T in Temp])  # equilibrium vacancy concentration: we'll need this to scale D_Onsager
for T in Temp:
    D=AnalyticalD(T)*1E-8 #Unit scaling
    print(T, D[0],D[1],D[2])
    D_Analytical.append([D[0],D[1],D[2]])
D_Analytical=np.array(D_Analytical)

100 3.63847485635e-68 3.63847485635e-68 7.68058421208e-69
200 1.44236638224e-37 1.44236638224e-37 7.14270905373e-38
300 2.3296989804e-27 2.3296989804e-27 1.49259710608e-27
400 2.9733358607e-22 2.9733358607e-22 2.15602919882e-22
500 3.44691069356e-19 3.44691069356e-19 2.68793529085e-19
600 3.80618149763e-17 3.80618149763e-17 3.11347801137e-17
700 1.09635937713e-15 1.09635937713e-15 9.27692209715e-16
800 1.36340995398e-14 1.36340995398e-14 1.18309989441e-14
900 9.68468074552e-14 9.68468074552e-14 8.56931026765e-14


Comparison of Onsager and analyitcal result, printing ratio of Onsager D/ Analytical D. We need to *now* multiply by the equilibrium vacancy concentration for the Onsager calculated version (since it gets multiplied by $c_\text{v}$). Now the agreement is excellent, with only "significant" deviation only happening at the smallest temperatures, where the diffusivity becomes very anisotropic (anisotropy ratio around 10, see a difference of $<10^{-3}$, which would be improved with denser $k$-point meshing).

In [13]:
D_Onsager_scaled = np.array([v*D for v,D in zip(vac, D_Onsager)])
Ratio=D_Onsager_scaled/(D_Analytical)
for i,T in enumerate(Temp):
    print (T, Ratio[i][0],Ratio[i][1],Ratio[i][2], c_rate(T)/Basal_rate(T))

100 0.999250692702 0.999250692702 1.00050381936 0.11730339367
200 0.999925682932 0.999925682932 1.0000545574 0.353256004263
300 0.999997193825 0.999997193825 1.00000162821 0.510131972868
400 1.00000095271 1.00000095271 0.999999679534 0.613026205459
500 1.00000033237 1.00000033237 1.0000001134 0.684473971015
600 0.999999749657 0.999999749657 1.00000045963 0.736674328539
700 1.00000020101 1.00000020101 0.999999989741 0.776380349624
800 1.00000036082 1.00000036082 0.999999689747 0.807558111738
900 0.999999660796 0.999999660796 1.00000001029 0.832670540646


KMC result for three temperatures, statisical error in KMC values is ~0.05%

In [14]:
# 700K, 800K, 900K
D_KMC=np.array([[1.10228325e-15,   1.10133965e-15, 9.30127592e-16],
                [1.36918534e-14,   1.37001681e-14,     1.18546593e-14],
                [9.73279952e-14,   9.73412524e-14,  8.58637944e-14]])

Comparison of Onsager (which matches the analytic result to $10^{-7}$) and KMC result, printing ratio of Onsager D/ KMC D. Agreement is $\sim 5\times10^{-3}$.

In [15]:
Ratio=D_Onsager_scaled[-3:]/D_KMC
for i,T in enumerate(Temp[-3:]):
    print (T, Ratio[i][0],Ratio[i][1],Ratio[i][2])

700 0.994626016055 0.995478186508 0.997381658362
800 0.995782240792 0.995177895609 0.998003820618
900 0.99505568162 0.994920161972 0.998012074321
